spring:
  application:
    name: gestionDeStock
  datasource:
    # Configuration du serveur local
    url: jdbc:postgresql://localhost:5432/gestiondestock
    username: postgres
    password: voahary
    driver-class-name: org.postgresql.Driver
    # Configuration du serveur en ligne (commentée par défaut)
    # url: jdbc:postgresql://ep-purple-block-a5tqz0kx.us-east-2.aws.neon.tech:5432/gestion_de_stock
    # username:
    # password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
